image: node:latest

pipelines:
  branches:
    master:
      - step:
          script:
            - apt-get update && apt-get install -y zip
            - npm install
            - npm run build
            - zip -r build.zip build
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"build.zip" -i