export const CONTAINERS_LIST_REQUEST = 'CONTAINERS_LIST_REQUEST';
export const CONTAINERS_LIST_SUCCESS = 'CONTAINERS_LIST_SUCCESS';
export const CONTAINERS_LIST_FAIL = 'CONTAINERS_LIST_FAIL';
export const CONTAINERS_START_REQUEST = 'CONTAINERS_START_REQUEST';
export const CONTAINERS_START_SUCCESS = 'CONTAINERS_START_SUCCESS';
export const CONTAINERS_START_FAIL = 'CONTAINERS_START_FAIL';
