export const CONTAINERS_LIST_REQUEST = 'CONTAINERS_LIST_REQUEST';
export const CONTAINERS_LIST_REQUEST_SUCCESS = 'CONTAINERS_LIST_REQUEST_SUCCESS';
export const CONTAINERS_LIST_REQUEST_FAIL = 'CONTAINERS_LIST_REQUEST_FAIL';
